### ISSUE TITLE
Modal with style containing top and topOffsetFixed causes it to jump up the page

### ISSUE THREAD

**Issue by cgaryet** [OfficeDev/office-ui-fabric-react#12271]
### Environment Information

- **Package version(s)**: 7.78.2
- **Browser and OS versions**: Chrome 80.0.3987.132

### Please provide a reproduction of the bug in a codepen:

[Codepen here](https://codepen.io/Tahlrok/pen/vYOdjWR)

#### Actual behavior:

Setting Top: number of a modal while topOffsetFixed: true is also set causes it to jump up the page by the amount set every time content is changed.  I'm a bit new to Fabric so if there's just a property somewhere I missed to do this instead of changing the style, feel free to close.

#### Expected behavior:

The top of the rectangle should remain fixed at the position it's set at.

### Priorities and help requested:

Requested priority: Normal

**Comment by aneeshack4** [comment]
@cgaryet Thanks for reaching out to us. I played around with your codepen a bit - if you take out the `topOffsetFixed` and the styles setting the `top` to `-200`, it's good: https://codepen.io/aneeshack4/pen/poJaKzy

**Comment by cgaryet** [comment]
@aneeshack4 right, they work independently okay, but I’d like the top of the modal to not be in the center of the page with the offset fixed in that location.

**Comment by aneeshack4** [comment]
@cgaryet I don't understand... can you elaborate or provide a visual/mockup? Why would the top of the modal not be in the center? Like do you want it off to the side as it is in the examples on the Fabric site? If so, the show code tab on there has example styles to show you how to achieve that.

**Comment by cgaryet** [comment]
@aneeshack4 hmm, the original idea for this was it was a detailslist that could grow in the container and I wanted it offset before it had to scroll, but I guess after messing with it for a bit it makes more sense to always have it centered regardless of its size.

Still, it seems like the dialog should in theory be able to do this, and there's a bug where it's adding the top offset amount every time it recalculates its fixed position.

**Comment by aneeshack4** [comment]
@cgaryet Hi, are you saying that you wanted to put a DetailsList inside this Modal? I still don't see why you would need to make it sticky to the top...
