### ISSUE TITLE
Official Documentation site is broken on some components sample

### ISSUE THREAD

**Issue by jonathanhotono** [OfficeDev/office-ui-fabric-react#1293]
### Bug Report

The official doc site seemed to be not displaying any samples:
https://dev.office.com/fabric#/components/searchbox
https://dev.office.com/fabric#/components/slider
https://dev.office.com/fabric#/components/spinner

**Comment by Jahnp** [comment]
Hi @jonathanhotono, can you try clearing your cache and refreshing, or trying in an Incognito/InPrivate window? This should have been fixed earlier today and is addressed in #1289. I'll go ahead and close for now since we believe we've fixed the issue, but please reopen if that isn't the case for you.

FYI @battletoilet

**Comment by jonathanhotono** [comment]
Thanks @Jahnp . I did used chrome incognito and opened in fresh edge browser. I reckon this is caused by the cache on CDN? If that's the case I'll wait for a few hours until the whole thing is refreshed.

**Comment by Jahnp** [comment]
That'd be my guess, yeah. Let me know if it still isn't working and we can crack this open and take a closer look.

**Comment by jonathanhotono** [comment]
Hi @Jahnp . I think the issue seemed still persists on my end. I tried to flushed my DNS, test it on Azure VM and the code seems still pointing to the broken one.

**Comment by jonathanhotono** [comment]
Hi @Jahnp, Unfortunately it's still showing errors on my side (incognito mode, dns updated to opendns).
![image](https://cloud.githubusercontent.com/assets/6864547/24401263/65c7a9f0-13ff-11e7-8318-e638e2868ec9.png)

https://dev.office.com/fabric#/components/searchbox
https://dev.office.com/fabric#/components/list
The script refers to 2017-3-28 date.
