### ISSUE TITLE
Callout slow performance

### ISSUE THREAD

**Issue by richardtagger** [OfficeDev/office-ui-fabric-react#3898]
### Bug Report

- __Package version(s)__: 5.45.1
- __Browser and OS versions__: Chrome Latest / MacOS High Sierra

Are you willing to submit a PR to fix? No

Requested priority:  Normal

Products/sites affected: Yammer

Yammer are trying to use Callout for type ahead suggestions in the message publisher. Looking at flame graphs when debugging performance reveals hundreds of milliseconds spent recalculating styles in Stylesheet.js and async.js. The calls originate from from Callout. Features that are highly interactive and re-render on keypresses etc may laggy performance. Disabling animations in CSS does not alleviate the problem as it appears to be spinning inside of positioning logic.

Use of Callout is here https://github.com/Microsoft/YamUI/blob/master/src/components/SuggestionsList/SuggestionsList.tsx#L82

![screen shot 2018-02-06 at 12 01 18 pm](https://user-images.githubusercontent.com/692240/35883665-dca9aaac-0b3c-11e8-9d5c-9562fdd7e0b5.png)

**Comment by craftytrickster** [comment]
I have also noticed very bad slowdowns with Callouts and Stylesheet.js, often taking an entire second to even appear on the screen, no matter how simple the content of the callout.

**Comment by craftytrickster** [comment]
Related ticket https://github.com/OfficeDev/office-ui-fabric-react/issues/4047

**Comment by joschect** [comment]
After some investigation and trial and error this should be fixed with #4140

**Comment by craftytrickster** [comment]
thanks!

**Comment by craftytrickster** [comment]
@joschect I just tried version 5.58.0 and the slowness of the callouts is definitely still there.

**Comment by joschect** [comment]
@craftytrickster Is there any improvement in speed? If there are no improvements it's back to square one. If it's faster, but not fast enough, I have some other ideas for continued gains.

**Comment by craftytrickster** [comment]
@joschect The changes weren't really noticeable, it was still hanging for about a second before rendering. Maybe, it was like 100ms faster, but it is hard to say.

**Comment by joschect** [comment]
@craftytrickster okay, I think I can fix this too but it will take a bit longer. This next fix is a bit more in depth.

**Comment by craftytrickster** [comment]
Thank you for looking into it.

**Comment by craftytrickster** [comment]
@joschect confirming that it is fixed now
