### ISSUE TITLE
DocumentCardTitle: "Maximum call stack size exceeded" caused by not truncating the long text

### ISSUE THREAD

**Issue by YusongLiu** [OfficeDev/office-ui-fabric-react#5308]
### Bug Report 
 
- __Package version(s)__: 5.112.0

#### Describe the issue:
 
In `DocumentCardTitle`, we have logic for deciding to truncate the title text or not in `_doesTitleOverflow`:
```
    // First check
    return (
      titleElement.scrollHeight > titleElement.clientHeight + TRUNCATION_VERTICAL_OVERFLOW_THRESHOLD ||
      titleElement.scrollWidth > titleElement.clientWidth
    );
  }
```

When trying to truncate it in `_startTruncation`, there is also a check for the length of the title text
```
    // Second check
    // If the title is really short, there's no need to truncate it
    if (originalTitle && originalTitle.length >= miniLength) {
````
We got infinite loop issue "Maximum call stack size exceeded" in a case where  `originalTitle` is `nospacenospacenospacenospacenospace` which has length 35 which is less than the miniLength which is 40. Actually it will render as the snapshot in certain mobile view:
![image](https://user-images.githubusercontent.com/15144072/41763816-d8a0108a-7631-11e8-8e32-1269bb9ebfa9.png)

It will pass the first check to try to truncate but will fail the second check before truncating so it never get truncated. In `_shrinkTitle`, the `setState` make it re-render and try to re-truncate and finally be a infinite loop.

#### Actual behavior:
 
Infinite loop when rendering DocumentCardTitle
 
#### Expected behavior:
 
No infinite loop

**Comment by dzearing** [comment]
@atneik Note that this is a 5.x build. Is this something that was resolved? Do you need to cherrypick something to the 5.x branch?

**Comment by YusongLiu** [comment]
Hi @atneik , do we have any update on this issue?

**Comment by atneik** [comment]
Looks like this bug was mis-assigned to me. @leddie24 @mikewheaton do you own or have context about this component?

**Comment by YusongLiu** [comment]
Hey @micahgodbolt , do we have some updates on this issue? We still see it in our page.

**Comment by micahgodbolt** [comment]
We haven't had a chance to dig into it yet. If you are familiar with the change that needs to happen, you are welcome to create a PR. I'll ping our current shield developer to see if we can get this prioritized

@cliffkoh

**Comment by cliffkoh** [comment]
I'm not sure why @atneik was tagged, but this bug was introduced in https://github.com/OfficeDev/office-ui-fabric-react/commit/d4159b20c9b143248cf52d1f3cdda24fd2e1caae in PR #4229 by @inateeg.

@inateeg, could you please look into this, as you introduced the bug and would be the most familiar with the scenario that necessitated the change you made in #4229?

**Comment by cliffkoh** [comment]
@YusongLiu, please work with @inateeg to get to a resolution on this.

**Comment by papigers** [comment]
I've also encountered this problem

**Comment by kenotron** [comment]
This is simply a case where there should have been a derived "shrunken title" and we're using state to calculate it, etc...

**Comment by kenotron** [comment]
@papigers are you referencing that this still repros in 6.x (master) ? I cannot repro this. 

@YusongLiu - it would be very helpful to have a codepen of this.

**Comment by papigers** [comment]
@kenotron After a lot of digging I've found out the cause was my sanitize css which gave `box-sizing: border-box;` to every element.
You can see codepen of this here:
https://codepen.io/papigers93/pen/jvMPOa

For some reason, the codepen doesn't show any exception on the console, even though the development build of react is used, but you can see the title is overflowing its container, which I assume is what caused this infinite loop somehow.

Either removing the sanitize css or adding `.ms-DocumentCardTitle { box-sizing: content-box; }` did the trick for me, but I assume you should find a better solution.

Either way, calling `setState` in `componentDidUpdate` is dangerous and should be avoided, even when bugs are not introduced (yet) :)

**Comment by kenotron** [comment]
That's a good point about the setState on componentDidUpdate (just typing it out should show that it will probably lead to infinite loop bugs :))

**Comment by lijunle** [comment]
This issue is still there. It should keep open.

**Comment by cliffkoh** [comment]
@lijunle please kindly provide a codepen repro as @kenotron requested.

**Comment by lijunle** [comment]
Codepen:

https://codepen.io/lijunle/pen/vVYRJa?editors=1010

GIF:

![resizecard-causereacterror](https://user-images.githubusercontent.com/1296500/46203787-6e95a880-c34d-11e8-8ba2-caed0479e399.gif)

**Comment by kenotron** [comment]
I think this gif is helpful - codepen has a different option in the "Change View" button. You must choose the left one to repro this.

**Comment by inateeg** [comment]
sorry I was distracted by other things... Will start looking into this now.

**Comment by inateeg** [comment]
Just clarify that my change there should not bee the root cause since the commit simply introduce the secondary truncation numbers but follow the exact same logic as before.  The fact YusongLiu said about 40 that is the original measurement.  But I will continue looking into this.

**Comment by micah** [comment]
wrong @micah

inateeg <notifications@github.com> writes:

> @Micah Godbolt<mailto:mgodbolt@microsoft.com> @Cliff Koh<mailto:Cliff.Koh@microsoft.com>  I took the close look on this and saw the root cause is that in componentDidUpdate() a function _shrinkTitle() that would setSate() continuously in some cases that Title in certain device that is checked as Overflow but not meet truncation standard.  That seems there from day one but has to be in some mobile device with title that is short than truncation length.  The recent change there only introduced secondary truncation numbers but not change those basic logic which has this defect under certain conditions.  To fix this,  seems either use the same checks for both overflow and need truncate or inside _shrinkTitle() either call _startTruncation() or setState but not both?  I think it perhaps best has Fabric dev to do the change?
>
> Thanks
> -ina
>
>
> From: Kenneth Chau <notifications@github.com>
> Sent: Friday, September 28, 2018 8:16 AM
> To: OfficeDev/office-ui-fabric-react <office-ui-fabric-react@noreply.github.com>
> Cc: Ina Teegan <inateeg@microsoft.com>; Mention <mention@noreply.github.com>
> Subject: Re: [OfficeDev/office-ui-fabric-react] DocumentCardTitle: "Maximum call stack size exceeded" caused by not truncating the long text (#5308)
>
>
> I think this gif is helpful - codepen has a different option in the "Change View" button. You must choose the left one to repro this.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FOfficeDev%2Foffice-ui-fabric-react%2Fissues%2F5308%23issuecomment-425469236&data=02%7C01%7Cinateeg%40microsoft.com%7Ce0a272f09e654959e6a408d625556347%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636737445998577583&sdata=q1JsVbiqea5zN6bWYZHFHoU4mvFQnSdt4a5GEGCGphk%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAT1rLj3qYs-IthNYB8xyeZLm1PBmQsD-ks5ufj1NgaJpZM4UzSTp&data=02%7C01%7Cinateeg%40microsoft.com%7Ce0a272f09e654959e6a408d625556347%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636737445998587583&sdata=WXXN4%2FORe5Sk1XMS86TY%2BMG8zefkhCqjr3jigMZ8eAY%3D&reserved=0>.
>
>
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/OfficeDev/office-ui-fabric-react/issues/5308#issuecomment-425592024
-- 
        micah
