### ISSUE TITLE
Picker callout acts strange when Enter is hit and the `itemLimit` is reached

### ISSUE THREAD

**Issue by basovic88** [OfficeDev/office-ui-fabric-react#5643]
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: Firefox 61.0.1 on Windows 10 64bit

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:
I use a `Picker` component with an `itemLimit`. When selecting the an item and hitting `Enter`, it reaches its `itemLimit` property. The Picker now ristricts further input by removing its Input field, but now the callout with suggestions stays open on the left-top corner of the viewport.

It seems that the callout with suggestions is ref'd to the Input field of the Picker. However, as the `itemLimit` is reached, the Input field disappears, hence the callout loses its ref and acts strange.

#### Expected behavior:

After hitting 'Enter' (whether the `itemLimit` has been reached or not) the list with suggestions disappears, until new input is been provided by the user.

### If applicable, please provide a codepen repro:
NA

**Comment by joschect** [comment]
Hey @basovic88 can you provide a bit more about a repro? We can reproduce it, but only if you select the same item twice. Do you have some other steps?

**Comment by ParadimeWeb** [comment]
The component needs to be controlled to see the issue. Here is the codepen demonstrating the issue.

https://codepen.io/paradimeweb/pen/eLzpxR

**Comment by basovic88** [comment]
I missed your request @joschect. Thanks @ParadimeWeb for providing the CodePen.

**Comment by micahgodbolt** [comment]
![picker](https://user-images.githubusercontent.com/1434956/44866499-475a9700-ac3a-11e8-90ad-297abc880cfc.gif)

**Comment by joschect** [comment]
That's pretty weird, I'll take a look.

**Comment by joschect** [comment]
The problem should be a pretty easy fix. It looks like when the suggestion is completed that it just doesn't set the suggestions to no longer be visible.

**Comment by ParadimeWeb** [comment]
Hello all,

Any updated on this bug? My users are starting to notice it more and more.

**Comment by micahgodbolt** [comment]
@joschect is this a quick fix you can knock out...or at least describe so that we can fix this?

**Comment by joschect** [comment]
@micahgodbolt this is a quick fix, I can get it done right now.

**Comment by ParadimeWeb** [comment]
It also does this with a DropDown and probably other components.

**Comment by ParadimeWeb** [comment]
OK, well this is breaking issue.
I added a controlled TextField to my codepen. Everytime you type in the field, you lose focus because it goes to the picker..!

https://codepen.io/paradimeweb/pen/eLzpxR

**Comment by dzearing** [comment]
All it takes is a re-render to move the focus back. @joschect this is indeed a breaking bug. I am digging in as well, but we need to fix this asap.

**Comment by dzearing** [comment]
Culprit is in componentWillReceiveProps. there is no reason to be stealing focus ever here!


BasePicker.tsx (see `this.resetFocus(focusIndex)`):
```
public componentWillReceiveProps(newProps: P): void {
    const newItems = newProps.selectedItems;

    if (newItems) {
      let focusIndex: number;

      // If there are less new items than old items then something was removed and we
      // should try to keep focus consistent
      if (newItems.length < this.state.items.length) {
        focusIndex = this.state.items.indexOf(this.selection.getSelection()[0]);
      }

      this.setState(
        {
          items: newProps.selectedItems
        },
        () => {
          // Need to reset focus in the same that way that we do if an item is selected by a non-controlled component
          // See _onSelectedItemsUpdated.
          this.resetFocus(focusIndex);
        }
      );
    }
  }

**Comment by dzearing** [comment]
Oh looks like it was fixed 5 hours ago.

https://github.com/OfficeDev/office-ui-fabric-react/commit/aab8f62851d91184b3c2ac7758dae2bc822e40bb

**Comment by dzearing** [comment]
PR here: https://github.com/OfficeDev/office-ui-fabric-react/pull/7587

**Comment by ParadimeWeb** [comment]
Tested and works now with v6.123.0

Thanks

**Comment by ParadimeWeb** [comment]
@dzearing 
After more tests, this is still a breaking issue. 
If you select an item from the picker first and then start typing in the TextField, you will lose focus and go to the picker.

If the picker is empty, it works fine, but if the picker has a selected value, any other component will lose focus to the picker!

You can still see this in the same CodePen
https://codepen.io/paradimeweb/pen/eLzpxR

**Comment by dzearing** [comment]
Re-opened. Thanks @joschect for jumping on this.

**Comment by ParadimeWeb** [comment]
@dzearing Would it be possible to make this urgent? It is a serious breaking issue.

**Comment by joschect** [comment]
@ParadimeWeb I should be able to get a pr in to fix this today.
