### ISSUE TITLE
The dropdown component does not tolerate a slight decreased space in height for the callout.

### ISSUE THREAD

**Issue by codeteq** [OfficeDev/office-ui-fabric-react#5918]
### Bug Report 
 
- __Package version(s)__: 6.49.0
- __Browser and OS versions__: Version 68.0.3440.106 (Offizieller Build) (64-Bit) / Win10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
No
 
Requested priority: (Blocking, High, Normal, Low) 
Normal
 
Products/sites affected: (if applicable)
Office Fabric Dropdown 
 
#### Describe the issue:
 
The dropdowns callout does not tolerate minor space issues regarding the height.
 Unfortunately sometimes the placement is not the expected behaviour as the available space in height is just slighlty less than needed.
 
#### Actual behavior:
 
When openening the dropdown with slightly less space in height for all items to display, it will place the callout at the next possible place that provides enough space (i.e. top or left/right). 
 
![image](https://user-images.githubusercontent.com/8259667/44037594-ff854db2-9f14-11e8-8640-3d34d9daa87f.png)

#### Expected behavior:

The callout of the dropdown shall tolerate less space in height and not place the dropdown on the left or right - except mobile.

![image](https://user-images.githubusercontent.com/8259667/44037607-0625d15a-9f15-11e8-9212-b50055051a92.png)

![image](https://user-images.githubusercontent.com/8259667/44037616-0ba40ec6-9f15-11e8-9a24-8fe58528de84.png)

Repro:
 
1. Go to https://developer.microsoft.com/en-us/fabric#/components/dropdown
2. Open the Dropdown of "Basic uncontrolled example:" - Dropdown opens correct
3. Decrease the height of your browser window. After a certain value the dropdown will open on the right side, instead of just tolerating the minor change.

**Comment by JasonGore** [comment]
What do you mean by "incorrect"? Is this a regression? If so, do you know which version it last behaved as you expected? 

The first two images you show, correct vs. incorrect, actually have the dropdown at different heights in the window, which affects layout. If I put the dropdown in the same position as your correct image, it behaves as shown in your expected image. 

The dropdown does not have enough height to appear below the dropdown in your actual behavior image. However, if you constrain the width of the window, the dropdown will no longer appear on the right and will appear over the dropdown component.

**Comment by codeteq** [comment]
Incorrect is maybe not the correct word. 
The dropdown component does not toelrate a slight decreased space in height for the callout.

There was a fix about that the dropdown does not populate over the dropdown component when the height is too less. This was fixed now. 

Despite this the callout should still tolerate a slight decrease in height.
A decrease of just a few pixel (or even a bit more) should not populate the callout on the left/right side.

Consider this case:
A list of dropdowns where only one dropdown has more items that the others. 
The behaviour of positioning the callout on the left/right side is not logical for just a few pixel decreased height. It totaly breaks the visual flow of the application.

**Comment by JasonGore** [comment]
I'm still not clear what the exact issue is because what I see [here](https://developer.microsoft.com/en-us/fabric#/components/dropdown) is exactly what is in your expected image: 

![image](https://user-images.githubusercontent.com/26070760/44054530-a4e47882-9ef7-11e8-9115-358cbd8766fe.png)

In this example there is very little space between the dropdown and the bottom of the browser and matches your expected result.

**Comment by codeteq** [comment]
When you now minize the height available for the dropdown it will open on the left/right.
Althoug there is just not enough space for one item!

The dropdown component should tolerate this edge case by just decreasing the height of the dropdown. Not showing it on the left/right side. I'm not saying it should never appear on the left/right sides, but it should tolerate some minor height decrease. At the moment its overreacting and breaks the visual flow.

**Actual**
![image](https://user-images.githubusercontent.com/8259667/44055237-05eaeb5a-9f45-11e8-901a-3bb36c69a08d.png)

**Expected**

![image](https://user-images.githubusercontent.com/8259667/44055233-028b8e92-9f45-11e8-94ba-56b25d4333f5.png)

**Comment by JasonGore** [comment]
Thanks for clarifying, it's obvious now with the scrollbar added. I'm not ever sure this was part of original design intent (unless you confirm this as a regression) so I'll tag this as a feature request for now. Thanks!

**Comment by codeteq** [comment]
@joechung-msft ah i knew that it must have worked sometime ago, thx!

Unfortunately if you use it with `directionalHintFixed: true ` it won't appear above the dropdown too:
![image](https://user-images.githubusercontent.com/8259667/44340800-4ed5af80-a486-11e8-9ac1-e224af2b4b32.png)
I support the left/side placement as far as there is **a tolerance** when just some items are invisible.
In this edge case it should still appear below or above

**Comment by joechung-msft** [comment]
That's a good point.  I suppose a better solution might be to reduce the size of the dropdown to avoid the likelihood of making repositioning above not an option.

**Comment by micahgodbolt** [comment]
@codeteq just wanted to check and see if there is still an ask here. Many things have changed since the post, and you mentioned some workarounds. Do you feel there is still an opportunity for improvement?

**Comment by codeteq** [comment]
@micahgodbolt 
thank you for the question. The current behaviour is quite accepted now.
So, from my side there is no further action needed.
