### ISSUE TITLE
Remove "sideeffects: true" from styling

### ISSUE THREAD

**Issue by ttaylor1218** [OfficeDev/office-ui-fabric-react#8242]
### Environment Information 
 
- __Package version(s)__: 6.152.1 
- __Browser and OS versions__: (Chrome 72, Windows 10)
`import * as React from "react";`
`import { Component } from "react";`
`import { render } from "react-dom";`
`import { Fabric } from 'office-ui-fabric-react/lib/Fabric';`
`export default class App`
`  	extends Component`
`{`
` 	render()`
`  	{`
`  		return <Fabric>WOHOO!!!</Fabric>;`
`  	}`
`}`
`const root = document.createElement("div");`
`root.id = "root";`
`document.body.appendChild(root);`
`render(<App />, root);`

 
#### Actual behavior:
Builds without error, doesn't render, Browser console shows following error:

TypeError: Cannot read property 'disableGlobalClassNames' of undefined
    at getGlobalClassNames.js:29
    at we (Fabric.styles.js:8)
    at ke (classNamesFunction.js:17)
    at t.render (Fabric.base.js:23)
    at t.e.(:1337/anonymous function) [as render] (http://localhost:1337/dist/main.js:46:24767)
    at Oo (react-dom.production.min.js:173)
    at No (react-dom.production.min.js:172)
    at Mo (react-dom.production.min.js:180)
    at Qa (react-dom.production.min.js:232)
    at Ka (react-dom.production.min.js:233)

#### Expected behavior:
 
 Builds without errors, displays WOHOO!!! in browser on render.
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: High

**Comment by ttaylor1218** [comment]
I was able to work around the issue by loading an empty theme:
`import { loadTheme } from '@uifabric/styling';`
`loadTheme({});`

However, this isn't required to make development build work.

**Comment by dzearing** [comment]
This should have been fixed in the latest styling package. The issue was a missing "sideEffects" entry in the package.json for the `theme.js` file.

**Comment by dzearing** [comment]
It could have been that we patched it and perhaps you didn't get the patch. I will make sure we update dependencies to minor bump it this weekend to be sure.

**Comment by dzearing** [comment]
Specifically this was fixed here:
https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/%40uifabric%2Fstyling_v6.44.1

If you make sure you have that version (6.44.1) of `@uifabric/styling`, this should go away.

Please let us know if not!

**Comment by yethee** [comment]
I have same issue with `office-ui-fabric-react@6.154.0`

Browser console:

```
TypeError: Cannot read property 'disableGlobalClassNames' of undefined
    at p (getGlobalClassNames.js:34)
    at Object.scope (Layer.styles.js:11)
    at styled.js:105
    at styles (styled.js:61)
    at classNamesFunction.js:22
    at t._getClassNames (Layer.base.js:160)
    at t._getLayerElement (Layer.base.js:177)
    at t.componentWillMount (Layer.base.js:62)
    at lo (react-dom.production.min.js:2853)
    at Ca (react-dom.production.min.js:3759)
```

Dependencies:

```bash
$ npm list @uifabric/styling

`-- office-ui-fabric-react@6.154.0
  +-- @uifabric/foundation@0.7.1
  | `-- @uifabric/styling@6.44.1  deduped
  +-- @uifabric/icons@6.4.0
  | `-- @uifabric/styling@6.44.1  deduped
  `-- @uifabric/styling@6.44.1
```

**Comment by aftab-hassan** [comment]
@yethee thanks for letting us know.

@dzearing does the `PR` you referenced above help fix the issue for `office-ui-fabric-react@6.154.0` as well?

**Comment by dzearing** [comment]
This looks like the correct version of styling... which is worrying. This is still the theme object missing. Yes my PR would certainly ensure theme is initialized. I am trying to make sure we're not regressing anything though with the PR, I'll try and get it in tonight.

**Comment by ttaylor1218** [comment]
Just now updated to build 6.155.0, and confirmed @uifabric/styling is @6.44.1. Still have the same issue with Webpack production builds. Basically unchanged since I reported last week.

**Comment by dzearing** [comment]
@ttaylor1218 is your project available to clone so that I can try your situation?

Alternatively:

1. find node_modules/@uifabric/styling/package.json
2. find the sideEffects section
3. edit the part that says `"lib/styles/theme.js"` and try `"**/theme.js"`

Does that change the result?

Alternatively, set sideEffects to true. I am assuming that will definitely fix but increase bundle size.

There is something definitely not right about webpack's handling of sideEffects, so my PR makes the initialization a requirement in the bundle, instead of an implication dependent on webpack treating it like a side effect.

**Comment by dzearing** [comment]
If I can't get the PR in tonight, i will prep a smaller reversion to sideEffects: true on this package.

The frustrating thing here is that i just am not reproing in isolation. it's some sort of combo of situations.

**Comment by ttaylor1218** [comment]
My project is on a private repo so you won't be able to get a clone. I was easily able to reproduce this by creating a real simple project which is how I isolated it to office-UI and use of the Fabric component.

Here are the files I used to reproduce:
[App.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/2959308/App.zip)

Thanks for your commitment to this. Let me know if this helps.

**Comment by dzearing** [comment]
We will get this fixed. I've prepped a plan A and B to get this done tonight. Thanks a ton for your patience. I've contacted Sean from webpack on this issue, so we will look more deeply into the root cause. Thank you for the App repro; got it reproing.

**Comment by dzearing** [comment]
@TheLarkInn If you try the App.zip above:
npm install
npm build
I had to make an index.html to load the script, then load it in a browser

It will fail with an error indicating basically that theme.js was not included.
Note that theme.js is listed in sideEffects in the package.json of `@uifabric/styling`.
if you edit sideEffects to equal true, it works.

It does not seem to me like sideEffects are working quite right.

**Comment by dzearing** [comment]
This wil

**Comment by ttaylor1218** [comment]
Pulled down the updated build @6.156.0 with @uifabric/styling@6.45.0. Confirmed it is now working as expected in both dev and prod Webpack builds.

Thank you everyone for your attention on this.
